// data.js - All game data definitions

const WEAPONS = {
  blaster: {
    id: 'blaster',
    name: 'Basic Blaster',
    icon: '🔫',
    damage: 10,
    fireRate: 3,
    projectileSpeed: 400,
    projectileLifetime: 1.5,
    projectileCount: 1,
    spread: 0,
    piercing: 0,
    areaDamage: 0,
    critChance: 0.05,
    critMultiplier: 2,
    color: '#ffff00',
    size: 8,
    description: 'Reliable basic blaster',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    icon: '💥',
    damage: 8,
    fireRate: 1.2,
    projectileSpeed: 350,
    projectileLifetime: 0.6,
    projectileCount: 5,
    spread: 0.4,
    piercing: 0,
    areaDamage: 0,
    critChance: 0.03,
    critMultiplier: 1.5,
    color: '#ff8800',
    size: 6,
    description: 'Fires multiple pellets in a spread',
  },
  magic_orb: {
    id: 'magic_orb',
    name: 'Magic Orb',
    icon: '🔮',
    damage: 15,
    fireRate: 2,
    projectileSpeed: 300,
    projectileLifetime: 2,
    projectileCount: 1,
    spread: 0,
    piercing: 2,
    areaDamage: 0,
    critChance: 0.1,
    critMultiplier: 2,
    color: '#8844ff',
    size: 12,
    description: 'Piercing magical projectile',
  },
  lightning: {
    id: 'lightning',
    name: 'Lightning',
    icon: '⚡',
    damage: 20,
    fireRate: 1.5,
    projectileSpeed: 600,
    projectileLifetime: 0.8,
    projectileCount: 1,
    spread: 0,
    piercing: 0,
    areaDamage: 50,
    critChance: 0.15,
    critMultiplier: 2.5,
    color: '#00ffff',
    size: 10,
    description: 'Fast lightning bolt with area damage',
  },
  orbiting_blades: {
    id: 'orbiting_blades',
    name: 'Orbiting Blades',
    icon: '🗡️',
    damage: 12,
    fireRate: 0,
    projectileSpeed: 0,
    projectileLifetime: 0,
    projectileCount: 3,
    spread: 0,
    piercing: 999,
    areaDamage: 0,
    critChance: 0.08,
    critMultiplier: 2,
    color: '#ff4444',
    size: 14,
    description: 'Blades orbit around the player',
    isOrbiting: true,
    orbitRadius: 60,
    orbitSpeed: 3,
  },
  rocket: {
    id: 'rocket',
    name: 'Explosive Rocket',
    icon: '🚀',
    damage: 30,
    fireRate: 0.8,
    projectileSpeed: 250,
    projectileLifetime: 2.5,
    projectileCount: 1,
    spread: 0,
    piercing: 0,
    areaDamage: 80,
    critChance: 0.05,
    critMultiplier: 1.5,
    color: '#ff4400',
    size: 14,
    description: 'Explosive rocket with area damage',
    isRocket: true,
  },
};

const EVOLUTIONS = {
  'rocket+explosion_mastery': {
    id: 'inferno_rocket',
    name: 'Inferno Rocket',
    icon: '🔥',
    damage: 50,
    fireRate: 1.2,
    projectileSpeed: 350,
    projectileLifetime: 2.5,
    projectileCount: 1,
    spread: 0,
    piercing: 0,
    areaDamage: 150,
    critChance: 0.1,
    critMultiplier: 2,
    color: '#ff2200',
    size: 18,
    description: 'Upgraded rocket with massive explosion',
    isRocket: true,
    evolution: true,
  },
  'magic_orb+pierce': {
    id: 'void_orb',
    name: 'Void Orb',
    icon: '🌀',
    damage: 25,
    fireRate: 2.5,
    projectileSpeed: 400,
    projectileLifetime: 2.5,
    projectileCount: 1,
    spread: 0,
    piercing: 5,
    areaDamage: 30,
    critChance: 0.15,
    critMultiplier: 2.5,
    color: '#4400aa',
    size: 16,
    description: 'Piercing void orb with area damage',
    evolution: true,
  },
  'shotgun+multishot': {
    id: 'hellstorm_shotgun',
    name: 'Hellstorm Shotgun',
    icon: '🌋',
    damage: 12,
    fireRate: 1.8,
    projectileSpeed: 400,
    projectileLifetime: 0.7,
    projectileCount: 8,
    spread: 0.5,
    piercing: 1,
    areaDamage: 0,
    critChance: 0.05,
    critMultiplier: 1.8,
    color: '#ff4400',
    size: 8,
    description: 'Devastating multi-pellet shotgun',
    evolution: true,
  },
};

const ENEMY_TYPES = {
  grunt: {
    id: 'grunt',
    name: 'Grunt',
    hp: 30,
    speed: 40,
    damage: 10,
    xp: 5,
    size: 24,
    color: '#ff4444',
    behavior: 'chase',
    sprite: 'enemy_1_walk',
  },
  runner: {
    id: 'runner',
    name: 'Runner',
    hp: 15,
    speed: 75,
    damage: 8,
    xp: 3,
    size: 18,
    color: '#ff8844',
    behavior: 'chase',
    sprite: 'enemy_2_walk',
  },
  tank: {
    id: 'tank',
    name: 'Tank',
    hp: 100,
    speed: 20,
    damage: 25,
    xp: 15,
    size: 36,
    color: '#8844ff',
    behavior: 'chase',
    sprite: 'enemy_3_walk',
  },
  ranged: {
    id: 'ranged',
    name: 'Ranged',
    hp: 40,
    speed: 30,
    damage: 15,
    xp: 10,
    size: 22,
    color: '#44ff44',
    behavior: 'ranged',
    attackRange: 200,
    attackCooldown: 2,
    projectileSpeed: 200,
    sprite: 'enemy_4_walk',
  },
  swarm: {
    id: 'swarm',
    name: 'Swarm',
    hp: 10,
    speed: 60,
    damage: 5,
    xp: 2,
    size: 14,
    color: '#ff44ff',
    behavior: 'swarm',
    sprite: 'enemy_5_walk',
  },
};

const BOSS_TYPES = {
  boss1: {
    id: 'boss1',
    name: 'Destroyer',
    hp: 2000,
    speed: 50,
    damage: 30,
    size: 64,
    color: '#ff0000',
    behavior: 'boss',
    sprite: 'boss',
    phases: [
      { hpThreshold: 1.0, attacks: ['charge', 'spawn_minions'] },
      { hpThreshold: 0.5, attacks: ['charge', 'spawn_minions', 'bullet_hell'] },
      { hpThreshold: 0.25, attacks: ['charge', 'spawn_minions', 'bullet_hell', 'laser_sweep'] },
    ],
  },
};

const UPGRADES = {
  damage_boost: {
    id: 'damage_boost',
    name: 'Damage Boost',
    icon: '⚔️',
    description: '+15% damage',
    maxLevel: 5,
    apply: (player) => { player.damageMultiplier += 0.15; },
  },
  fire_rate: {
    id: 'fire_rate',
    name: 'Fire Rate',
    icon: '🔥',
    description: '+10% fire rate',
    maxLevel: 5,
    apply: (player) => { player.fireRateMultiplier += 0.10; },
  },
  speed_boost: {
    id: 'speed_boost',
    name: 'Speed Boost',
    icon: '👟',
    description: '+10% movement speed',
    maxLevel: 5,
    apply: (player) => { player.speedMultiplier += 0.10; },
  },
  health_boost: {
    id: 'health_boost',
    name: 'Health Boost',
    icon: '❤️',
    description: '+25 max HP and heal 25',
    maxLevel: 5,
    apply: (player) => { player.maxHp += 25; player.hp = Math.min(player.hp + 25, player.maxHp); },
  },
  xp_boost: {
    id: 'xp_boost',
    name: 'XP Boost',
    icon: '💎',
    description: '+20% XP gain',
    maxLevel: 5,
    apply: (player) => { player.xpMultiplier += 0.20; },
  },
  magnet: {
    id: 'magnet',
    name: 'Magnet',
    icon: '🧲',
    description: '+30% pickup range',
    maxLevel: 5,
    apply: (player) => { player.magnetRange += 30; },
  },
  crit_chance: {
    id: 'crit_chance',
    name: 'Critical Chance',
    icon: '🎯',
    description: '+5% critical hit chance',
    maxLevel: 5,
    apply: (player) => { player.critChance += 0.05; },
  },
  crit_damage: {
    id: 'crit_damage',
    name: 'Critical Damage',
    icon: '💢',
    description: '+25% critical damage',
    maxLevel: 5,
    apply: (player) => { player.critMultiplier += 0.25; },
  },
  armor: {
    id: 'armor',
    name: 'Armor',
    icon: '🛡️',
    description: '-10% damage taken',
    maxLevel: 5,
    apply: (player) => { player.armorMultiplier *= 0.90; },
  },
  regen: {
    id: 'regen',
    name: 'Regeneration',
    icon: '💚',
    description: '+1 HP per second',
    maxLevel: 5,
    apply: (player) => { player.regenRate += 1; },
  },
  projectile_speed: {
    id: 'projectile_speed',
    name: 'Projectile Speed',
    icon: '💨',
    description: '+15% projectile speed',
    maxLevel: 5,
    apply: (player) => { player.projectileSpeedMultiplier += 0.15; },
  },
  multishot: {
    id: 'multishot',
    name: 'Multishot',
    icon: '🔱',
    description: '+1 projectile for all weapons',
    maxLevel: 3,
    apply: (player) => { player.multishot += 1; },
  },
  explosion_mastery: {
    id: 'explosion_mastery',
    name: 'Explosion Mastery',
    icon: '💥',
    description: '+25% explosion radius and damage',
    maxLevel: 3,
    apply: (player) => { player.explosionMultiplier += 0.25; },
    evolutionKey: 'explosion_mastery',
  },
  pierce: {
    id: 'pierce',
    name: 'Pierce',
    icon: '🗡️',
    description: '+1 pierce for all projectiles',
    maxLevel: 3,
    apply: (player) => { player.pierceBonus += 1; },
    evolutionKey: 'pierce',
  },
};

const DIFFICULTY_SCALING = {
  hpMultiplier: (time) => 1 + time * 0.02,
  speedMultiplier: (time) => 1 + time * 0.005,
  damageMultiplier: (time) => 1 + time * 0.01,
  spawnRate: (time) => Math.max(0.3, 1 - time * 0.005),
  eliteChance: (time) => Math.min(0.3, time * 0.002),
};

const XP_CURVE = (level) => Math.floor(20 * Math.pow(1.3, level - 1));

const WORLD = {
  width: 3000,
  height: 3000,
  tileSize: 32,
};

const COLORS = {
  floor: '#2a4a2a',
  floorAlt: '#2d4d2d',
  rock: '#666666',
  tree: '#1a5a1a',
  treeTrunk: '#4a3020',
  water: '#2244aa',
  spawn: '#ff0000',
};
